listening-port=3478
tls-listening-port=5349
listening-ip=0.0.0.0
external-ip=127.0.0.1
realm=webrtc.local
fingerprint
lt-cred-mech
use-auth-secret
static-auth-secret=replace_with_real_secret
total-quota=2000
bps-capacity=0
stale-nonce
no-loopback-peers
no-multicast-peers
